---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Menu
- type: document
  path: _data/navbar.yml
  label: Site Menu
- type: heading
  label: Page configuration
- type: directory
  path: _front-page-callouts
  label: Front Page Announcements
  create: documents
  match: "**/*"
  templates:
  - front-page-callout
- type: document
  path: index.html
  label: Home Page
- type: directory
  path: _page-sections
  label: Page sections
  create: documents
  match: "**/*"
  templates:
  - page-section
- type: heading
  label: Content
- type: directory
  path: _people
  label: People
  create: documents
  match: "**/*"
  templates:
  - person
- type: directory
  path: _news-activities
  label: News and Activities
  create: documents
  match: "**/*"
  templates:
  - news-activity
- type: directory
  path: _outreach-engagement
  label: Outreach Projects
  create: documents
  match: "**/*"
  templates:
  - outreach-project
- type: directory
  path: _research
  label: Research Projects
  create: documents
  match: "**/*"
  templates:
  - research
- type: directory
  path: _objective-teams
  label: Objective Teams
  create: documents
  match: "**/*"
  templates:
  - objective-team
- type: directory
  path: _stakeholder-groups
  label: Stakeholder Groups
  create: documents
  match: "**/*"
- type: directory
  path: _courses
  label: Courses
  create: documents
  match: "**/*"
  templates:
  - course
- type: heading
  label: to be removed
- type: document
  path: _includes/footer-content.md
  label: Footer
upload_dir: assets/img
public_path: assets/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
