---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Menu
- type: document
  path: _data/navbar.yml
  label: Site Menu
- type: heading
  label: Page Configuration
- type: document
  path: index.html
  label: Home Page
- type: document
  path: industry-career
  label: industry & career
- type: heading
  label: Content
- type: directory
  path: _front-page-callouts
  label: Front Page Callouts
  create: all
  match: "**/*"
  templates:
  - front-page-callout
- type: directory
  path: _page-sections
  label: Page sections
  create: documents
  match: "**/*"
  templates:
  - page-section
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: _programs
  label: Programs
  create: none
  match: "**/*"
- type: directory
  path: _team
  label: Team
  create: all
  match: "**/*"
upload_dir: assets/img
public_path: assets/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
