---
label: Page Configuration
hide_body: true
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: boolean
  name: enable-banner
  label: enable-banner
- type: boolean
  name: enable-header
  label: enable-header
- type: text
  name: permalink
  label: permalink
